using System.Text;

namespace WorkoutLogger.Api.Common;

/// <summary>
/// Reduces a free-text exercise name to a stable lookup key.
/// </summary>
/// <remarks>
/// This is the whole basis of exercise deduplication: "Bench Press",
/// "bench-press" and "BENCH  PRESS" must all collapse to "bench press" or the
/// same lift fragments into separate progression lines. The seeded
/// NormalizedName/NormalizedAlias columns are generated by these exact rules.
/// </remarks>
public static class TextNormalizer
{
    public static string Normalize(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        var builder = new StringBuilder(value.Length);
        var lastWasSpace = true; // leading separators are dropped

        foreach (var c in value)
        {
            if (char.IsLetterOrDigit(c))
            {
                builder.Append(char.ToLowerInvariant(c));
                lastWasSpace = false;
            }
            else if (!lastWasSpace)
            {
                builder.Append(' ');
                lastWasSpace = true;
            }
        }

        // A trailing separator leaves one space behind.
        if (builder.Length > 0 && builder[^1] == ' ')
        {
            builder.Length--;
        }

        return builder.ToString();
    }
}
