-- Canonical exercise catalogue + common aliases. Idempotent via INSERT OR IGNORE
-- against the UNIQUE name columns, so this runs on every startup harmlessly.
-- NormalizedName/NormalizedAlias must match TextNormalizer output exactly:
-- lowercased, non-alphanumerics collapsed to single spaces, trimmed.

INSERT OR IGNORE INTO Exercise (CanonicalName, NormalizedName, MuscleGroup, Modality, IsUnresolved, CreatedAtUtc)
VALUES
    ('Barbell Bench Press',          'barbell bench press',          'Chest',      'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Incline Barbell Bench Press',  'incline barbell bench press',  'Chest',      'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Dumbbell Bench Press',         'dumbbell bench press',         'Chest',      'Dumbbell',   0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Incline Dumbbell Bench Press', 'incline dumbbell bench press', 'Chest',      'Dumbbell',   0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Barbell Back Squat',           'barbell back squat',           'Quads',      'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Barbell Front Squat',          'barbell front squat',          'Quads',      'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Conventional Deadlift',        'conventional deadlift',        'Posterior',  'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Romanian Deadlift',            'romanian deadlift',            'Hamstrings', 'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Sumo Deadlift',                'sumo deadlift',                'Posterior',  'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Overhead Press',               'overhead press',               'Shoulders',  'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Seated Dumbbell Shoulder Press','seated dumbbell shoulder press','Shoulders', 'Dumbbell',   0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Barbell Row',                  'barbell row',                  'Back',       'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Dumbbell Row',                 'dumbbell row',                 'Back',       'Dumbbell',   0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Seated Cable Row',             'seated cable row',             'Back',       'Cable',      0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Lat Pulldown',                 'lat pulldown',                 'Back',       'Cable',      0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Pull Up',                      'pull up',                      'Back',       'Bodyweight', 0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Chin Up',                      'chin up',                      'Back',       'Bodyweight', 0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Dip',                          'dip',                          'Triceps',    'Bodyweight', 0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Leg Press',                    'leg press',                    'Quads',      'Machine',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Leg Extension',                'leg extension',                'Quads',      'Machine',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Lying Leg Curl',               'lying leg curl',               'Hamstrings', 'Machine',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Walking Lunge',                'walking lunge',                'Quads',      'Dumbbell',   0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Bulgarian Split Squat',        'bulgarian split squat',        'Quads',      'Dumbbell',   0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Hip Thrust',                   'hip thrust',                   'Glutes',     'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Standing Calf Raise',          'standing calf raise',          'Calves',     'Machine',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Barbell Curl',                 'barbell curl',                 'Biceps',     'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Dumbbell Curl',                'dumbbell curl',                'Biceps',     'Dumbbell',   0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Hammer Curl',                  'hammer curl',                  'Biceps',     'Dumbbell',   0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Triceps Pushdown',             'triceps pushdown',             'Triceps',    'Cable',      0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Skullcrusher',                 'skullcrusher',                 'Triceps',    'Barbell',    0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Lateral Raise',                'lateral raise',                'Shoulders',  'Dumbbell',   0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Face Pull',                    'face pull',                    'Rear Delts', 'Cable',      0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Plank',                        'plank',                        'Core',       'Bodyweight', 0, strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    ('Hanging Leg Raise',            'hanging leg raise',            'Core',       'Bodyweight', 0, strftime('%Y-%m-%dT%H:%M:%SZ','now'));

WITH a (Canonical, NormalizedAlias, RawAlias) AS (
    VALUES
        ('barbell bench press',          'bench',                      'Bench'),
        ('barbell bench press',          'bench press',                'Bench Press'),
        ('barbell bench press',          'bb bench',                   'BB Bench'),
        ('barbell bench press',          'flat bench',                 'Flat Bench'),
        ('incline barbell bench press',  'incline bench',              'Incline Bench'),
        ('incline barbell bench press',  'incline bench press',        'Incline Bench Press'),
        ('dumbbell bench press',         'db bench',                   'DB Bench'),
        ('dumbbell bench press',         'dumbbell press',             'Dumbbell Press'),
        ('incline dumbbell bench press', 'incline db bench',           'Incline DB Bench'),
        ('incline dumbbell bench press', 'incline dumbbell press',     'Incline Dumbbell Press'),
        ('barbell back squat',           'squat',                      'Squat'),
        ('barbell back squat',           'back squat',                 'Back Squat'),
        ('barbell back squat',           'bb squat',                   'BB Squat'),
        ('barbell front squat',          'front squat',                'Front Squat'),
        ('conventional deadlift',        'deadlift',                   'Deadlift'),
        ('conventional deadlift',        'dl',                         'DL'),
        ('romanian deadlift',            'rdl',                        'RDL'),
        ('romanian deadlift',            'romanian dl',                'Romanian DL'),
        ('sumo deadlift',                'sumo dl',                    'Sumo DL'),
        ('overhead press',               'ohp',                        'OHP'),
        ('overhead press',               'military press',             'Military Press'),
        ('overhead press',               'standing press',             'Standing Press'),
        ('overhead press',               'shoulder press',             'Shoulder Press'),
        ('seated dumbbell shoulder press','db shoulder press',         'DB Shoulder Press'),
        ('seated dumbbell shoulder press','seated db press',           'Seated DB Press'),
        ('barbell row',                  'bent over row',              'Bent Over Row'),
        ('barbell row',                  'bb row',                     'BB Row'),
        ('barbell row',                  'barbell bent over row',      'Barbell Bent Over Row'),
        ('dumbbell row',                 'db row',                     'DB Row'),
        ('dumbbell row',                 'one arm row',                'One Arm Row'),
        ('dumbbell row',                 'single arm dumbbell row',    'Single Arm Dumbbell Row'),
        ('seated cable row',             'cable row',                  'Cable Row'),
        ('lat pulldown',                 'pulldown',                   'Pulldown'),
        ('lat pulldown',                 'lat pull down',              'Lat Pull Down'),
        ('pull up',                      'pullup',                     'Pullup'),
        ('pull up',                      'pull ups',                   'Pull Ups'),
        ('chin up',                      'chinup',                     'Chinup'),
        ('chin up',                      'chin ups',                   'Chin Ups'),
        ('dip',                          'dips',                       'Dips'),
        ('dip',                          'parallel bar dip',           'Parallel Bar Dip'),
        ('leg press',                    'leg press machine',          'Leg Press Machine'),
        ('leg extension',                'leg extensions',             'Leg Extensions'),
        ('leg extension',                'quad extension',             'Quad Extension'),
        ('lying leg curl',               'leg curl',                   'Leg Curl'),
        ('lying leg curl',               'hamstring curl',             'Hamstring Curl'),
        ('walking lunge',                'lunge',                      'Lunge'),
        ('walking lunge',                'lunges',                     'Lunges'),
        ('bulgarian split squat',        'split squat',                'Split Squat'),
        ('bulgarian split squat',        'bss',                        'BSS'),
        ('bulgarian split squat',        'rear foot elevated split squat', 'Rear Foot Elevated Split Squat'),
        ('hip thrust',                   'barbell hip thrust',         'Barbell Hip Thrust'),
        ('standing calf raise',          'calf raise',                 'Calf Raise'),
        ('standing calf raise',          'calf raises',                'Calf Raises'),
        ('barbell curl',                 'bicep curl',                 'Bicep Curl'),
        ('barbell curl',                 'bb curl',                    'BB Curl'),
        ('dumbbell curl',                'db curl',                    'DB Curl'),
        ('dumbbell curl',                'dumbbell bicep curl',        'Dumbbell Bicep Curl'),
        ('hammer curl',                  'hammer curls',               'Hammer Curls'),
        ('triceps pushdown',             'pushdown',                   'Pushdown'),
        ('triceps pushdown',             'tricep pushdown',            'Tricep Pushdown'),
        ('triceps pushdown',             'rope pushdown',              'Rope Pushdown'),
        ('skullcrusher',                 'skull crusher',              'Skull Crusher'),
        ('skullcrusher',                 'lying tricep extension',     'Lying Tricep Extension'),
        ('lateral raise',                'side raise',                 'Side Raise'),
        ('lateral raise',                'lateral raises',             'Lateral Raises'),
        ('lateral raise',                'db lateral raise',           'DB Lateral Raise'),
        ('face pull',                    'face pulls',                 'Face Pulls'),
        ('plank',                        'planks',                     'Planks'),
        ('hanging leg raise',            'leg raise',                  'Leg Raise'),
        ('hanging leg raise',            'hanging knee raise',         'Hanging Knee Raise')
)
INSERT OR IGNORE INTO ExerciseAlias (ExerciseId, NormalizedAlias, RawAlias, CreatedAtUtc)
SELECT e.Id, a.NormalizedAlias, a.RawAlias, strftime('%Y-%m-%dT%H:%M:%SZ','now')
FROM a
JOIN Exercise e ON e.NormalizedName = a.Canonical;
